#!/bin/bash

cur_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
if [ $cur_branch = $1 ]; then
  echo "Already on branch $1. Won't do anything"
  exit 0
fi
cur_path=$(pwd)
git checkout $1
if [ "$?" -eq "0" ]; then
  cd Release && rm -fr * && \
  cmake .. && make -j7
  cd $cur_path
  pwd
  cd "Release-mxe" && rm -fr * #&& \
  /opt/mxe/usr/bin/i686-w64-mingw32.static-cmake .. && make -j7
  if [ $cur_branch = "prokop" ]; then
    printf "[General]\npresetDirectory=/home/christoph/humanist/annotate-cassiodor\npresetLanguage=1" > /home/christoph/.config/annotate/mainwindow.ini
  elif [ $cur_branch = "master" ]; then
    printf "[General]\npresetDirectory=/home/christoph/humanist/annotate-prokop\npresetLanguage=0" > /home/christoph/.config/annotate/mainwindow.ini
  fi
fi
